esphome:
  name: esp32c3

esp32:
  board: esp32-c3-devkitm-1
  #board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    version: latest


external_components:
  - source:  rigol
    components: [ rigol,adc ]

rigol:
  pin: GPIO00
  frequency: 1000

#sensor:
#  - platform: adc
#    pin: GPIO34
#    name: "Living Room Brightness"
#    update_interval: 60s



web_server:
  
api:

ota:
  platform: esphome

wifi:
  fast_connect: true
  output_power: 8.5dB
  power_save_mode: none
  networks:
    - ssid: "Futurama"
      password: !secret wifi_ap_password
  ap:
    ssid: "C3 Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:


logger:
#  level: INFO
  level: DEBUG
#  level: VERBOSE

#sensor:
#  - platform: wifi_signal
#    name: "WiFi Signal Sensor"
#    update_interval: 2s
